export const FOLDER = {
  LOAD: "FOLDER_LOAD",
  LOAD_SUCCESS: "FOLDER_LOAD_SUCCESS",
  LOAD_FAILED: "FOLDER_LOAD_FAILED",
  SELECTED_FOLDER: "SELECTED_FOLDER",
  SELECTED_NODES: "SELECTED_NODES",
  SET_FILES_PATH: "SET_FILES_PATH",
  CLEAR: "FOLDER_CLEAR"
};

export const AUTH = {
  LOAD: "AUTH_LOAD",
  LOAD_SUCCESS: "AUTH_LOAD_SUCCESS",
  LOAD_FAILED: "AUTH_LOAD_FAILED",
  CLEAR: "AUTH_CLEAR"
};

export const UI = {
  OPEN_SIDEBAR: "OPEN_SIDEBAR",
  CLOSE_SIDEBAR: "CLOSE_SIDEBAR",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  SET_ACTION_TYPE: "SET_ACTION_TYPE",
  SET_FILE_CONTEXT_POSITION: "SET_FILE_CONTEXT_POSITION",
  SET_FOLDER_CONTEXT_POSITION: "SET_FOLDER_CONTEXT_POSITION",
  SET_COMPANY_LISTING_POSITION: "SET_COMPANY_LISTING_POSITION"
};

export const COMPANY = {
  LOAD: "COMPANY_LOAD",
  LOAD_SUCCESS: "COMPANY_LOAD_SUCCESS",
  LOAD_FAILED: "COMPANY_LOAD_FAILED",
  SELECTED_COMPANY: "SELECTED_COMPANY",
  CLEAR: "COMPANY_CLEAR"
};

export const DOCUMENT = {
  LOAD: "DOCUMENT_LOAD",
  LOAD_SUCCESS: "DOCUMENT_LOAD_SUCCESS",
  LOAD_FAILED: "DOCUMENT_LOAD_FAILED",
  DOCUMENT_INVOICE: "DOCUMENT_INVOICE",
  DOCUMENT_RECEIPT: "DOCUMENT_RECEIPT",
  DOCUMENT_DEBIT_NOTE: "DOCUMENT_DEBIT_NOTE",
  DOCUMENT_CREDIT_NOTE: "DOCUMENT_CREDIT_NOTE",
  DOCUMENT_IMPORT_PERMIT: "DOCUMENT_IMPORT_PERMIT",
  CLEAR: "DOCUMENT_CLEAR"
};

export const ADD_FOLDER = {
  LOAD: "ADD_FOLDER_LOAD",
  LOAD_SUCCESS: "ADD_FOLDER_LOAD_SUCCESS",
  LOAD_FAILED: "ADD_FOLDER_LOAD_FAILED",
  SET_FOLDER_NAME: "ADD_FOLDER_NAME",
  CLEAR: "ADD_FOLDER_CLEAR"
};

export const RENAME_FOLDER = {
  LOAD: "RENAME_FOLDER_LOAD",
  LOAD_SUCCESS: "RENAME_FOLDER_LOAD_SUCCESS",
  LOAD_FAILED: "RENAME_FOLDER_LOAD_FAILED",
  SET_FOLDER_NAME: "RENAME_FOLDER_NAME",
  CLEAR: "RENAME_FOLDER_CLEAR"
};

export const MOVE_FOLDER = {
  LOAD: "MOVE_FOLDER_LOAD",
  MOVE_FILE: "MOVE_FILE",
  LOAD_SUCCESS: "MOVE_FOLDER_LOAD_SUCCESS",
  LOAD_FAILED: "MOVE_FOLDER_LOAD_FAILED",
  SET_FOLDER_PATH: "MOVE_FOLDER_PATH",
  SET_FOLDER_NODES: "MOVE_FOLDER_NODES",
  CLEAR: "MOVE_FOLDER_CLEAR"
};

export const DELETE_FOLDER = {
  LOAD: "DELETE_FOLDER_LOAD",
  DELETE_FILE: "DELETE_FILE",
  LOAD_SUCCESS: "DELETE_FOLDER_LOAD_SUCCESS",
  LOAD_FAILED: "DELETE_FOLDER_LOAD_FAILED",
  SET_FOLDER_PATH: "DELETE_FOLDER_PATH",
  CLEAR: "DELETE_FOLDER_CLEAR"
};
